---
- name: remove kdumps
  hosts: PW
  remote_user: root

  tasks:

  - name: Find kdump files
    find:
      paths: /boot
      patterns: "*kdump.img"
    register: fdel

  - name: Remove file kdump's
    file:
     path: "{{ item['path'] }}"
     state: absent
     #force: yes
    with_items: "{{ fdel.files }}"
    become: yes
